console.log("1st statement!");
console.log("2nd statement!");
debugger;
console.log("3rd statement!");
console.log("4th statement!");
console.log("5th statement!");
debugger;
console.log("6th statement!");
console.log("7th statement!");
console.log("8th statement!");
debugger;
console.log("9th statement!");
console.log("10th statement!");
debugger;
console.log("11th statement!");
debugger;